module.exports = `POSTGRES_HOST=postgres
POSTGRES_USER=graph-node
POSTGRES_PASSWORD=let-me-in
POSTGRES_DB=graph-node

DB_IDLE_CONN_TIMEOUT=30s
DB_TIMEOUT=30s

WATCHERS_MAX_COUNT=100
WATCHERS_CALL_TIMEOUT=20s
WATCHERS_LOG_LEVEL=info
LOG_LEVEL=info

ETH_MAINNET_PROVIDER: `
