module.exports = `MAINNET_PROVIDER=
BASE_PROVIDER=
ARBITRUM_PROVIDER=
OPTIMISM_PROVIDER=
POLYGON_PROVIDER=
BSC_PROVIDER=
AVALANCHE_PROVIDER=
ZERO_PROVIDER=

SEPOLIA_PROVIDER=

DEFAULT_PROVIDER=SEPOLIA

LOG_LEVEL=debug`
