
      config0:
        - &network eth
        - &sourceAddress '0xc3d688b66703497daa19211eedff47f25384cdc3'
        - &startBlock 15331586
        
      config1:
        - &network eth
        - &sourceAddress '0xa17581a9e3356d9a858b789d68b4d866e593ae94'
        - &startBlock 16400710
        